
name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: Restart backend with PM2
      run: /home/ubuntu/.nvm/versions/node/v20.17.0/bin/pm2 restart backend
    - name: Restart Nginx
      run: sudo systemctl restart nginx
